logger:
    noise: loud
    level: 6
    location: stdout
    levels:
        config: 1

cache:
    hostaddr: "$MONGO_PORT_27017_TCP_ADDR"
    port: "$MONGO_PORT_27017_TCP_PORT"
    database: test

auth:
    googlekey: "419303763151-c57q5rf3omkr7n3f45a5tfavisovo8jr.apps.googleusercontent.com"
    googlesecret: "gDkhFl3VXnVbMBGk7B_MeI2z"
    callbackurl: "http://local.drama9.com:8181/auth/callback"
    sessionkey: "auth"

server:
    bindaddress: "0.0.0.0:8181"

session:
    sessionname: "ftc_session"
    secret: "secret_123"

database:
    hostaddr: "$MARIADB_PORT_3306_TCP_ADDR"
    port: "$MARIADB_PORT_3306_TCP_PORT"
    username: "$MARIADB_ENV_MYSQL_USER"
    password: "$MARIADB_ENV_MYSQL_PASSWORD"
    database: "$MARIADB_ENV_MYSQL_DATABASE"
    prefix: "test_"
